[providers]
nodejs = "18"
python = "3.11"

[phases.setup]
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "npm install",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "npm run build",
    "python scripts/init_app.py"
]

[start]
cmd = "npm start" 